# Total interval in seconds for clearing items/entities
clear-interval: 600

# First warning time in seconds before clearing
warning-1: 30

# Second warning time in seconds before clearing
warning-2: 10

# Toggle whether to clear named entities
clear-named-entities: false

# The amount of seconds an entity needs to be alive before it can be removed by ClearLag
minimum-lived-seconds: 5

# The radius in blocks around each player where mobs and items will not despawn.
player-safe-radius: 24

# A list of entities to not delete
excluded-entities:
  - "player"
  - "item_frame"
  - "armor_stand"
  - "villager"